INSERT INTO City(id,name) VALUES (1, 'Puerto Nare');
INSERT INTO City(id,name) VALUES (2, 'Puerto Triunfo');
INSERT INTO City(id,name) VALUES (3, 'Remedios');
INSERT INTO City(id,name) VALUES (4, 'Retiro');
INSERT INTO City(id,name) VALUES (5, 'Rionegro');
INSERT INTO City(id,name) VALUES (6, 'Sabanalarga');
INSERT INTO City(id,name) VALUES (7, 'Sabaneta');
INSERT INTO City(id,name) VALUES (8, 'Salgar');
INSERT INTO City(id,name) VALUES (9, 'San Francisco');
INSERT INTO City(id,name) VALUES (10, 'San Jerónimo');
INSERT INTO City(id,name) VALUES (11, 'San Luis');
INSERT INTO City(id,name) VALUES (12, 'San Pedro');
INSERT INTO City(id,name) VALUES (13, 'San Rafael');
INSERT INTO City(id,name) VALUES (14, 'San Roque');
INSERT INTO City(id,name) VALUES (15, 'San Vicente');
INSERT INTO City(id,name) VALUES (16, 'Santa Bárbara');
INSERT INTO City(id,name) VALUES (17, 'Santo Domingo');
INSERT INTO City(id,name) VALUES (18, 'El Santuario');
INSERT INTO City(id,name) VALUES (19, 'Segovia');
INSERT INTO City(id,name) VALUES (20, 'Sopetrán');
INSERT INTO City(id,name) VALUES (21, 'Támesis');
INSERT INTO City(id,name) VALUES (22, 'Tarazá');
INSERT INTO City(id,name) VALUES (23, 'Tarso');
INSERT INTO City(id,name) VALUES (24, 'Titiribí');
INSERT INTO City(id,name) VALUES (25, 'Toledo');
INSERT INTO City(id,name) VALUES (26, 'Turbo');
INSERT INTO City(id,name) VALUES (27, 'Uramita');
INSERT INTO City(id,name) VALUES (28, 'Urrao');
INSERT INTO City(id,name) VALUES (29, 'Valdivia');
INSERT INTO City(id,name) VALUES (30, 'Valparaíso');
INSERT INTO City(id,name) VALUES (31, 'Vegachí');
INSERT INTO City(id,name) VALUES (32, 'Venecia');
INSERT INTO City(id,name) VALUES (33, 'Yalí');
INSERT INTO City(id,name) VALUES (34, 'Yarumal');
INSERT INTO City(id,name) VALUES (35, 'Yolombó');
INSERT INTO City(id,name) VALUES (36, 'Yondó');
INSERT INTO City(id,name) VALUES (37, 'Zaragoza');
INSERT INTO City(id,name) VALUES (38, 'San Pedro de Uraba');
INSERT INTO City(id,name) VALUES (39, 'Santafé de Antioquia');
INSERT INTO City(id,name) VALUES (40, 'Santa Rosa de Osos');
INSERT INTO City(id,name) VALUES (41, 'San Andrés de Cuerquía');
INSERT INTO City(id,name) VALUES (42, 'Vigía del Fuerte');
INSERT INTO City(id,name) VALUES (43, 'San José de La Montaña');
INSERT INTO City(id,name) VALUES (44, 'San Juan de Urabá');
INSERT INTO City(id,name) VALUES (45, 'El Carmen de Viboral');
INSERT INTO City(id,name) VALUES (46, 'San Carlos');
INSERT INTO City(id,name) VALUES (47, 'Frontino');
INSERT INTO City(id,name) VALUES (48, 'Granada');
INSERT INTO City(id,name) VALUES (49, 'Jardín');
INSERT INTO City(id,name) VALUES (50, 'Sonsón');
INSERT INTO City(id,name) VALUES (51, 'Arauquita');
INSERT INTO City(id,name) VALUES (52, 'Cravo Norte');
INSERT INTO City(id,name) VALUES (53, 'Fortul');
INSERT INTO City(id,name) VALUES (54, 'Puerto Rondón');
INSERT INTO City(id,name) VALUES (55, 'Saravena');
INSERT INTO City(id,name) VALUES (56, 'Tame');
INSERT INTO City(id,name) VALUES (57, 'Arauca');
INSERT INTO City(id,name) VALUES (58, 'Barranquilla');
INSERT INTO City(id,name) VALUES (59, 'Baranoa');
INSERT INTO City(id,name) VALUES (60, 'Candelaria');
INSERT INTO City(id,name) VALUES (61, 'Galapa');
INSERT INTO City(id,name) VALUES (62, 'Luruaco');
INSERT INTO City(id,name) VALUES (63, 'Malambo');
INSERT INTO City(id,name) VALUES (64, 'Manatí');
INSERT INTO City(id,name) VALUES (65, 'Piojó');
INSERT INTO City(id,name) VALUES (66, 'Polonuevo');
INSERT INTO City(id,name) VALUES (67, 'Sabanagrande');
INSERT INTO City(id,name) VALUES (68, 'Sabanalarga');
INSERT INTO City(id,name) VALUES (69, 'Santa Lucía');
INSERT INTO City(id,name) VALUES (70, 'Santo Tomás');
INSERT INTO City(id,name) VALUES (71, 'Soledad');
INSERT INTO City(id,name) VALUES (72, 'Suan');
INSERT INTO City(id,name) VALUES (73, 'Tubará');
INSERT INTO City(id,name) VALUES (74, 'Usiacurí');
INSERT INTO City(id,name) VALUES (75, 'Juan de Acosta');
INSERT INTO City(id,name) VALUES (76, 'Palmar de Varela');
INSERT INTO City(id,name) VALUES (77, 'Campo de La Cruz');
INSERT INTO City(id,name) VALUES (78, 'Repelón');
INSERT INTO City(id,name) VALUES (79, 'Puerto Colombia');
INSERT INTO City(id,name) VALUES (80, 'Ponedera');
INSERT INTO City(id,name) VALUES (81, 'Bogotá D.C.');
INSERT INTO City(id,name) VALUES (82, 'Achí');
INSERT INTO City(id,name) VALUES (83, 'Arenal');
INSERT INTO City(id,name) VALUES (84, 'Arjona');
INSERT INTO City(id,name) VALUES (85, 'Arroyohondo');
INSERT INTO City(id,name) VALUES (86, 'Calamar');
INSERT INTO City(id,name) VALUES (87, 'Cantagallo');
INSERT INTO City(id,name) VALUES (88, 'Cicuco');
INSERT INTO City(id,name) VALUES (89, 'Córdoba');
INSERT INTO City(id,name) VALUES (90, 'Clemencia');
INSERT INTO City(id,name) VALUES (91, 'El Guamo');
INSERT INTO City(id,name) VALUES (92, 'Magangué');
INSERT INTO City(id,name) VALUES (93, 'Mahates');
INSERT INTO City(id,name) VALUES (94, 'Margarita');
INSERT INTO City(id,name) VALUES (95, 'Montecristo');
INSERT INTO City(id,name) VALUES (96, 'Mompós');
INSERT INTO City(id,name) VALUES (97, 'Morales');
INSERT INTO City(id,name) VALUES (98, 'Norosí');
INSERT INTO City(id,name) VALUES (99, 'Pinillos');
INSERT INTO City(id,name) VALUES (100, 'Regidor');
INSERT INTO City(id,name) VALUES (101, 'Río Viejo');
INSERT INTO City(id,name) VALUES (102, 'San Estanislao');
INSERT INTO City(id,name) VALUES (103, 'San Fernando');
INSERT INTO City(id,name) VALUES (104, 'San Juan Nepomuceno');
INSERT INTO City(id,name) VALUES (105, 'Santa Catalina');
INSERT INTO City(id,name) VALUES (106, 'Santa Rosa');
INSERT INTO City(id,name) VALUES (107, 'Simití');
INSERT INTO City(id,name) VALUES (108, 'Soplaviento');
INSERT INTO City(id,name) VALUES (109, 'Talaigua Nuevo');
INSERT INTO City(id,name) VALUES (110, 'Tiquisio');
INSERT INTO City(id,name) VALUES (111, 'Turbaco');
INSERT INTO City(id,name) VALUES (112, 'Turbaná');
INSERT INTO City(id,name) VALUES (113, 'Villanueva');
INSERT INTO City(id,name) VALUES (114, 'Barranco de Loba');
INSERT INTO City(id,name) VALUES (115, 'Santa Rosa del Sur');
INSERT INTO City(id,name) VALUES (116, 'Hatillo de Loba');
INSERT INTO City(id,name) VALUES (117, 'El Carmen de Bolívar');
INSERT INTO City(id,name) VALUES (118, 'San Martín de Loba');
INSERT INTO City(id,name) VALUES (119, 'Altos del Rosario');
INSERT INTO City(id,name) VALUES (120, 'San Jacinto del Cauca');
INSERT INTO City(id,name) VALUES (121, 'San Pablo de Borbur');
INSERT INTO City(id,name) VALUES (122, 'San Jacinto');
INSERT INTO City(id,name) VALUES (123, 'El Peñón');
INSERT INTO City(id,name) VALUES (124, 'Cartagena');
INSERT INTO City(id,name) VALUES (125, 'María la Baja');
INSERT INTO City(id,name) VALUES (126, 'San Cristóbal');
INSERT INTO City(id,name) VALUES (127, 'Zambrano');
INSERT INTO City(id,name) VALUES (128, 'Tununguá');
INSERT INTO City(id,name) VALUES (129, 'Motavita');
INSERT INTO City(id,name) VALUES (130, 'Ciénega');
INSERT INTO City(id,name) VALUES (131, 'Tunja');
INSERT INTO City(id,name) VALUES (132, 'Almeida');
INSERT INTO City(id,name) VALUES (133, 'Aquitania');
INSERT INTO City(id,name) VALUES (134, 'Arcabuco');
INSERT INTO City(id,name) VALUES (135, 'Berbeo');
INSERT INTO City(id,name) VALUES (136, 'Betéitiva');
INSERT INTO City(id,name) VALUES (137, 'Boavita');
INSERT INTO City(id,name) VALUES (138, 'Boyacá');
INSERT INTO City(id,name) VALUES (139, 'Briceño');
INSERT INTO City(id,name) VALUES (140, 'Buena Vista');
INSERT INTO City(id,name) VALUES (141, 'Busbanzá');
INSERT INTO City(id,name) VALUES (142, 'Caldas');
INSERT INTO City(id,name) VALUES (143, 'Campohermoso');
INSERT INTO City(id,name) VALUES (144, 'Cerinza');
INSERT INTO City(id,name) VALUES (145, 'Chinavita');
INSERT INTO City(id,name) VALUES (146, 'Chiquinquirá');
INSERT INTO City(id,name) VALUES (147, 'Chiscas');
INSERT INTO City(id,name) VALUES (148, 'Chita');
INSERT INTO City(id,name) VALUES (149, 'Chitaraque');
INSERT INTO City(id,name) VALUES (150, 'Chivatá');
INSERT INTO City(id,name) VALUES (151, 'Cómbita');
INSERT INTO City(id,name) VALUES (152, 'Coper');
INSERT INTO City(id,name) VALUES (153, 'Corrales');
INSERT INTO City(id,name) VALUES (154, 'Covarachía');
INSERT INTO City(id,name) VALUES (155, 'Cubará');
INSERT INTO City(id,name) VALUES (156, 'Cucaita');
INSERT INTO City(id,name) VALUES (157, 'Cuítiva');
INSERT INTO City(id,name) VALUES (158, 'Chíquiza');
INSERT INTO City(id,name) VALUES (159, 'Chivor');
INSERT INTO City(id,name) VALUES (160, 'Duitama');
INSERT INTO City(id,name) VALUES (161, 'El Cocuy');
INSERT INTO City(id,name) VALUES (162, 'El Espino');
INSERT INTO City(id,name) VALUES (163, 'Firavitoba');
INSERT INTO City(id,name) VALUES (164, 'Floresta');
INSERT INTO City(id,name) VALUES (165, 'Gachantivá');
INSERT INTO City(id,name) VALUES (166, 'Gameza');
INSERT INTO City(id,name) VALUES (167, 'Garagoa');
INSERT INTO City(id,name) VALUES (168, 'Guacamayas');
INSERT INTO City(id,name) VALUES (169, 'Guateque');
INSERT INTO City(id,name) VALUES (170, 'Guayatá');
INSERT INTO City(id,name) VALUES (171, 'Güicán');
INSERT INTO City(id,name) VALUES (172, 'Iza');
INSERT INTO City(id,name) VALUES (173, 'Jenesano');
INSERT INTO City(id,name) VALUES (174, 'Jericó');
INSERT INTO City(id,name) VALUES (175, 'Labranzagrande');
INSERT INTO City(id,name) VALUES (176, 'La Capilla');
INSERT INTO City(id,name) VALUES (177, 'La Victoria');
INSERT INTO City(id,name) VALUES (178, 'Macanal');
INSERT INTO City(id,name) VALUES (179, 'Maripí');
INSERT INTO City(id,name) VALUES (180, 'Miraflores');
INSERT INTO City(id,name) VALUES (181, 'Mongua');
INSERT INTO City(id,name) VALUES (182, 'Monguí');
INSERT INTO City(id,name) VALUES (183, 'Moniquirá');
INSERT INTO City(id,name) VALUES (184, 'Muzo');
INSERT INTO City(id,name) VALUES (185, 'Nobsa');
INSERT INTO City(id,name) VALUES (186, 'Nuevo Colón');
INSERT INTO City(id,name) VALUES (187, 'Oicatá');
INSERT INTO City(id,name) VALUES (188, 'Otanche');
INSERT INTO City(id,name) VALUES (189, 'Pachavita');
INSERT INTO City(id,name) VALUES (190, 'Páez');
INSERT INTO City(id,name) VALUES (191, 'Paipa');
INSERT INTO City(id,name) VALUES (192, 'Pajarito');
INSERT INTO City(id,name) VALUES (193, 'Panqueba');
INSERT INTO City(id,name) VALUES (194, 'Pauna');
INSERT INTO City(id,name) VALUES (195, 'Paya');
INSERT INTO City(id,name) VALUES (196, 'Pesca');
INSERT INTO City(id,name) VALUES (197, 'Pisba');
INSERT INTO City(id,name) VALUES (198, 'Puerto Boyacá');
INSERT INTO City(id,name) VALUES (199, 'Quípama');
INSERT INTO City(id,name) VALUES (200, 'Ramiriquí');
INSERT INTO City(id,name) VALUES (201, 'Ráquira');
INSERT INTO City(id,name) VALUES (202, 'Rondón');
INSERT INTO City(id,name) VALUES (203, 'Saboyá');
INSERT INTO City(id,name) VALUES (204, 'Sáchica');
INSERT INTO City(id,name) VALUES (205, 'Samacá');
INSERT INTO City(id,name) VALUES (206, 'San Eduardo');
INSERT INTO City(id,name) VALUES (207, 'San Mateo');
INSERT INTO City(id,name) VALUES (208, 'Santana');
INSERT INTO City(id,name) VALUES (209, 'Santa María');
INSERT INTO City(id,name) VALUES (210, 'Santa Sofía');
INSERT INTO City(id,name) VALUES (211, 'Sativanorte');
INSERT INTO City(id,name) VALUES (212, 'Sativasur');
INSERT INTO City(id,name) VALUES (213, 'Siachoque');
INSERT INTO City(id,name) VALUES (214, 'Soatá');
INSERT INTO City(id,name) VALUES (215, 'Socotá');
INSERT INTO City(id,name) VALUES (216, 'Socha');
INSERT INTO City(id,name) VALUES (217, 'Sogamoso');
INSERT INTO City(id,name) VALUES (218, 'Somondoco');
INSERT INTO City(id,name) VALUES (219, 'Sora');
INSERT INTO City(id,name) VALUES (220, 'Sotaquirá');
INSERT INTO City(id,name) VALUES (221, 'Soracá');
INSERT INTO City(id,name) VALUES (222, 'Susacón');
INSERT INTO City(id,name) VALUES (223, 'Sutamarchán');
INSERT INTO City(id,name) VALUES (224, 'Sutatenza');
INSERT INTO City(id,name) VALUES (225, 'Tasco');
INSERT INTO City(id,name) VALUES (226, 'Tenza');
INSERT INTO City(id,name) VALUES (227, 'Tibaná');
INSERT INTO City(id,name) VALUES (228, 'Tinjacá');
INSERT INTO City(id,name) VALUES (229, 'Tipacoque');
INSERT INTO City(id,name) VALUES (230, 'Toca');
INSERT INTO City(id,name) VALUES (231, 'Tópaga');
INSERT INTO City(id,name) VALUES (232, 'Tota');
INSERT INTO City(id,name) VALUES (233, 'Turmequé');
INSERT INTO City(id,name) VALUES (234, 'Tutazá');
INSERT INTO City(id,name) VALUES (235, 'Umbita');
INSERT INTO City(id,name) VALUES (236, 'Ventaquemada');
INSERT INTO City(id,name) VALUES (237, 'Viracachá');
INSERT INTO City(id,name) VALUES (238, 'Zetaquira');
INSERT INTO City(id,name) VALUES (239, 'Togüí');
INSERT INTO City(id,name) VALUES (240, 'Villa de Leyva');
INSERT INTO City(id,name) VALUES (241, 'Paz de Río');
INSERT INTO City(id,name) VALUES (242, 'Santa Rosa de Viterbo');
INSERT INTO City(id,name) VALUES (243, 'San Pablo de Borbur');
INSERT INTO City(id,name) VALUES (244, 'San Luis de Gaceno');
INSERT INTO City(id,name) VALUES (245, 'San José de Pare');
INSERT INTO City(id,name) VALUES (246, 'San Miguel de Sema');
INSERT INTO City(id,name) VALUES (247, 'Tuta');
INSERT INTO City(id,name) VALUES (248, 'Tibasosa');
INSERT INTO City(id,name) VALUES (249, 'La Uvita');
INSERT INTO City(id,name) VALUES (250, 'Belén');
INSERT INTO City(id,name) VALUES (251, 'Manizales');
INSERT INTO City(id,name) VALUES (252, 'Aguadas');
INSERT INTO City(id,name) VALUES (253, 'Anserma');
INSERT INTO City(id,name) VALUES (254, 'Aranzazu');
INSERT INTO City(id,name) VALUES (255, 'Belalcázar');
INSERT INTO City(id,name) VALUES (256, 'Chinchiná');
INSERT INTO City(id,name) VALUES (257, 'Filadelfia');
INSERT INTO City(id,name) VALUES (258, 'La Dorada');
INSERT INTO City(id,name) VALUES (259, 'La Merced');
INSERT INTO City(id,name) VALUES (260, 'Manzanares');
INSERT INTO City(id,name) VALUES (261, 'Marmato');
INSERT INTO City(id,name) VALUES (262, 'Marulanda');
INSERT INTO City(id,name) VALUES (263, 'Neira');
INSERT INTO City(id,name) VALUES (264, 'Norcasia');
INSERT INTO City(id,name) VALUES (265, 'Pácora');
INSERT INTO City(id,name) VALUES (266, 'Palestina');
INSERT INTO City(id,name) VALUES (267, 'Pensilvania');
INSERT INTO City(id,name) VALUES (268, 'Riosucio');
INSERT INTO City(id,name) VALUES (269, 'Risaralda');
INSERT INTO City(id,name) VALUES (270, 'Salamina');
INSERT INTO City(id,name) VALUES (271, 'Samaná');
INSERT INTO City(id,name) VALUES (272, 'San José');
INSERT INTO City(id,name) VALUES (273, 'Supía');
INSERT INTO City(id,name) VALUES (274, 'Victoria');
INSERT INTO City(id,name) VALUES (275, 'Villamaría');
INSERT INTO City(id,name) VALUES (276, 'Viterbo');
INSERT INTO City(id,name) VALUES (277, 'Marquetalia');
INSERT INTO City(id,name) VALUES (278, 'Florencia');
INSERT INTO City(id,name) VALUES (279, 'Albania');
INSERT INTO City(id,name) VALUES (280, 'Curillo');
INSERT INTO City(id,name) VALUES (281, 'El Doncello');
INSERT INTO City(id,name) VALUES (282, 'El Paujil');
INSERT INTO City(id,name) VALUES (283, 'Morelia');
INSERT INTO City(id,name) VALUES (284, 'Puerto Rico');
INSERT INTO City(id,name) VALUES (285, 'Solano');
INSERT INTO City(id,name) VALUES (286, 'Solita');
INSERT INTO City(id,name) VALUES (287, 'Valparaíso');
INSERT INTO City(id,name) VALUES (288, 'San José del Fragua');
INSERT INTO City(id,name) VALUES (289, 'Belén de Los Andaquies');
INSERT INTO City(id,name) VALUES (290, 'Cartagena del Chairá');
INSERT INTO City(id,name) VALUES (291, 'Milán');
INSERT INTO City(id,name) VALUES (292, 'La Montañita');
INSERT INTO City(id,name) VALUES (293, 'San Vicente del Caguán');
INSERT INTO City(id,name) VALUES (294, 'Yopal');
INSERT INTO City(id,name) VALUES (295, 'Aguazul');
INSERT INTO City(id,name) VALUES (296, 'Chámeza');
INSERT INTO City(id,name) VALUES (297, 'Hato Corozal');
INSERT INTO City(id,name) VALUES (298, 'La Salina');
INSERT INTO City(id,name) VALUES (299, 'Monterrey');
INSERT INTO City(id,name) VALUES (300, 'Pore');
INSERT INTO City(id,name) VALUES (301, 'Recetor');
INSERT INTO City(id,name) VALUES (302, 'Sabanalarga');
INSERT INTO City(id,name) VALUES (303, 'Sácama');
INSERT INTO City(id,name) VALUES (304, 'Tauramena');
INSERT INTO City(id,name) VALUES (305, 'Trinidad');
INSERT INTO City(id,name) VALUES (306, 'Villanueva');
INSERT INTO City(id,name) VALUES (307, 'San Luis de Gaceno');
INSERT INTO City(id,name) VALUES (308, 'Paz de Ariporo');
INSERT INTO City(id,name) VALUES (309, 'Nunchía');
INSERT INTO City(id,name) VALUES (310, 'Maní');
INSERT INTO City(id,name) VALUES (311, 'Támara');
INSERT INTO City(id,name) VALUES (312, 'Orocué');
INSERT INTO City(id,name) VALUES (313, 'Popayán');
INSERT INTO City(id,name) VALUES (314, 'Almaguer');
INSERT INTO City(id,name) VALUES (315, 'Argelia');
INSERT INTO City(id,name) VALUES (316, 'Balboa');
INSERT INTO City(id,name) VALUES (317, 'Bolívar');
INSERT INTO City(id,name) VALUES (318, 'Buenos Aires');
INSERT INTO City(id,name) VALUES (319, 'Cajibío');
INSERT INTO City(id,name) VALUES (320, 'Caldono');
INSERT INTO City(id,name) VALUES (321, 'Caloto');
INSERT INTO City(id,name) VALUES (322, 'Corinto');
INSERT INTO City(id,name) VALUES (323, 'El Tambo');
INSERT INTO City(id,name) VALUES (324, 'Florencia');
INSERT INTO City(id,name) VALUES (325, 'Guachené');
INSERT INTO City(id,name) VALUES (326, 'Guapi');
INSERT INTO City(id,name) VALUES (327, 'Inzá');
INSERT INTO City(id,name) VALUES (328, 'Jambaló');
INSERT INTO City(id,name) VALUES (329, 'La Sierra');
INSERT INTO City(id,name) VALUES (330, 'La Vega');
INSERT INTO City(id,name) VALUES (331, 'López');
INSERT INTO City(id,name) VALUES (332, 'Mercaderes');
INSERT INTO City(id,name) VALUES (333, 'Miranda');
INSERT INTO City(id,name) VALUES (334, 'Morales');
INSERT INTO City(id,name) VALUES (335, 'Padilla');
INSERT INTO City(id,name) VALUES (336, 'Patía');
INSERT INTO City(id,name) VALUES (337, 'Piamonte');
INSERT INTO City(id,name) VALUES (338, 'Piendamó');
INSERT INTO City(id,name) VALUES (339, 'Puerto Tejada');
INSERT INTO City(id,name) VALUES (340, 'Puracé');
INSERT INTO City(id,name) VALUES (341, 'Rosas');
INSERT INTO City(id,name) VALUES (342, 'Santa Rosa');
INSERT INTO City(id,name) VALUES (343, 'Silvia');
INSERT INTO City(id,name) VALUES (344, 'Sotara');
INSERT INTO City(id,name) VALUES (345, 'Suárez');
INSERT INTO City(id,name) VALUES (346, 'Sucre');
INSERT INTO City(id,name) VALUES (347, 'Timbío');
INSERT INTO City(id,name) VALUES (348, 'Timbiquí');
INSERT INTO City(id,name) VALUES (349, 'Toribio');
INSERT INTO City(id,name) VALUES (350, 'Totoró');
INSERT INTO City(id,name) VALUES (351, 'Villa Rica');
INSERT INTO City(id,name) VALUES (352, 'Puerto López');
INSERT INTO City(id,name) VALUES (353, 'Puerto Lleras');
INSERT INTO City(id,name) VALUES (354, 'Puerto Rico');
INSERT INTO City(id,name) VALUES (355, 'Santander de Quilichao');
INSERT INTO City(id,name) VALUES (356, 'San Sebastián');
INSERT INTO City(id,name) VALUES (357, 'Páez');
INSERT INTO City(id,name) VALUES (358, 'Valledupar');
INSERT INTO City(id,name) VALUES (359, 'Aguachica');
INSERT INTO City(id,name) VALUES (360, 'Agustín Codazzi');
INSERT INTO City(id,name) VALUES (361, 'Astrea');
INSERT INTO City(id,name) VALUES (362, 'Becerril');
INSERT INTO City(id,name) VALUES (363, 'Bosconia');
INSERT INTO City(id,name) VALUES (364, 'Chimichagua');
INSERT INTO City(id,name) VALUES (365, 'Chiriguaná');
INSERT INTO City(id,name) VALUES (366, 'Curumaní');
INSERT INTO City(id,name) VALUES (367, 'El Copey');
INSERT INTO City(id,name) VALUES (368, 'El Paso');
INSERT INTO City(id,name) VALUES (369, 'Gamarra');
INSERT INTO City(id,name) VALUES (370, 'González');
INSERT INTO City(id,name) VALUES (371, 'La Gloria');
INSERT INTO City(id,name) VALUES (372, 'Manaure');
INSERT INTO City(id,name) VALUES (373, 'Pailitas');
INSERT INTO City(id,name) VALUES (374, 'Pelaya');
INSERT INTO City(id,name) VALUES (375, 'Pueblo Bello');
INSERT INTO City(id,name) VALUES (376, 'La Paz');
INSERT INTO City(id,name) VALUES (377, 'San Alberto');
INSERT INTO City(id,name) VALUES (378, 'San Diego');
INSERT INTO City(id,name) VALUES (379, 'San Martín');
INSERT INTO City(id,name) VALUES (380, 'Tamalameque');
INSERT INTO City(id,name) VALUES (381, 'Río de Oro');
INSERT INTO City(id,name) VALUES (382, 'La Jagua de Ibirico');
INSERT INTO City(id,name) VALUES (383, 'Istmina');
INSERT INTO City(id,name) VALUES (384, 'Quibdó');
INSERT INTO City(id,name) VALUES (385, 'Acandí');
INSERT INTO City(id,name) VALUES (386, 'Alto Baudo');
INSERT INTO City(id,name) VALUES (387, 'Atrato');
INSERT INTO City(id,name) VALUES (388, 'Bagadó');
INSERT INTO City(id,name) VALUES (389, 'Bahía Solano');
INSERT INTO City(id,name) VALUES (390, 'Bajo Baudó');
INSERT INTO City(id,name) VALUES (391, 'Bojaya');
INSERT INTO City(id,name) VALUES (392, 'Cértegui');
INSERT INTO City(id,name) VALUES (393, 'Condoto');
INSERT INTO City(id,name) VALUES (394, 'Juradó');
INSERT INTO City(id,name) VALUES (395, 'Lloró');
INSERT INTO City(id,name) VALUES (396, 'Medio Atrato');
INSERT INTO City(id,name) VALUES (397, 'Medio Baudó');
INSERT INTO City(id,name) VALUES (398, 'Medio San Juan');
INSERT INTO City(id,name) VALUES (399, 'Nóvita');
INSERT INTO City(id,name) VALUES (400, 'Nuquí');
INSERT INTO City(id,name) VALUES (401, 'Río Iro');
INSERT INTO City(id,name) VALUES (402, 'Río Quito');
INSERT INTO City(id,name) VALUES (403, 'Riosucio');
INSERT INTO City(id,name) VALUES (404, 'Sipí');
INSERT INTO City(id,name) VALUES (405, 'Unguía');
INSERT INTO City(id,name) VALUES (406, 'El Litoral del San Juan');
INSERT INTO City(id,name) VALUES (407, 'El Cantón del San Pablo');
INSERT INTO City(id,name) VALUES (408, 'El Carmen de Atrato');
INSERT INTO City(id,name) VALUES (409, 'San José del Palmar');
INSERT INTO City(id,name) VALUES (410, 'Belén de Bajira');
INSERT INTO City(id,name) VALUES (411, 'Carmen del Darien');
INSERT INTO City(id,name) VALUES (412, 'Tadó');
INSERT INTO City(id,name) VALUES (413, 'Unión Panamericana');
INSERT INTO City(id,name) VALUES (414, 'San Bernardo del Viento');
INSERT INTO City(id,name) VALUES (415, 'Montería');
INSERT INTO City(id,name) VALUES (416, 'Ayapel');
INSERT INTO City(id,name) VALUES (417, 'Buenavista');
INSERT INTO City(id,name) VALUES (418, 'Canalete');
INSERT INTO City(id,name) VALUES (419, 'Cereté');
INSERT INTO City(id,name) VALUES (420, 'Chimá');
INSERT INTO City(id,name) VALUES (421, 'Chinú');
INSERT INTO City(id,name) VALUES (422, 'Cotorra');
INSERT INTO City(id,name) VALUES (423, 'Lorica');
INSERT INTO City(id,name) VALUES (424, 'Los Córdobas');
INSERT INTO City(id,name) VALUES (425, 'Momil');
INSERT INTO City(id,name) VALUES (426, 'Moñitos');
INSERT INTO City(id,name) VALUES (427, 'Planeta Rica');
INSERT INTO City(id,name) VALUES (428, 'Pueblo Nuevo');
INSERT INTO City(id,name) VALUES (429, 'Puerto Escondido');
INSERT INTO City(id,name) VALUES (430, 'Purísima');
INSERT INTO City(id,name) VALUES (431, 'Sahagún');
INSERT INTO City(id,name) VALUES (432, 'San Andrés Sotavento');
INSERT INTO City(id,name) VALUES (433, 'San Antero');
INSERT INTO City(id,name) VALUES (434, 'San Pelayo');
INSERT INTO City(id,name) VALUES (435, 'Tierralta');
INSERT INTO City(id,name) VALUES (436, 'Tuchín');
INSERT INTO City(id,name) VALUES (437, 'Valencia');
INSERT INTO City(id,name) VALUES (438, 'San José de Uré');
INSERT INTO City(id,name) VALUES (439, 'Ciénaga de Oro');
INSERT INTO City(id,name) VALUES (440, 'San Carlos');
INSERT INTO City(id,name) VALUES (441, 'Montelíbano');
INSERT INTO City(id,name) VALUES (442, 'La Apartada');
INSERT INTO City(id,name) VALUES (443, 'Puerto Libertador');
INSERT INTO City(id,name) VALUES (444, 'Anapoima');
INSERT INTO City(id,name) VALUES (445, 'Arbeláez');
INSERT INTO City(id,name) VALUES (446, 'Beltrán');
INSERT INTO City(id,name) VALUES (447, 'Bituima');
INSERT INTO City(id,name) VALUES (448, 'Bojacá');
INSERT INTO City(id,name) VALUES (449, 'Cabrera');
INSERT INTO City(id,name) VALUES (450, 'Cachipay');
INSERT INTO City(id,name) VALUES (451, 'Cajicá');
INSERT INTO City(id,name) VALUES (452, 'Caparrapí');
INSERT INTO City(id,name) VALUES (453, 'Caqueza');
INSERT INTO City(id,name) VALUES (454, 'Chaguaní');
INSERT INTO City(id,name) VALUES (455, 'Chipaque');
INSERT INTO City(id,name) VALUES (456, 'Choachí');
INSERT INTO City(id,name) VALUES (457, 'Chocontá');
INSERT INTO City(id,name) VALUES (458, 'Cogua');
INSERT INTO City(id,name) VALUES (459, 'Cota');
INSERT INTO City(id,name) VALUES (460, 'Cucunubá');
INSERT INTO City(id,name) VALUES (461, 'El Colegio');
INSERT INTO City(id,name) VALUES (462, 'El Rosal');
INSERT INTO City(id,name) VALUES (463, 'Fomeque');
INSERT INTO City(id,name) VALUES (464, 'Fosca');
INSERT INTO City(id,name) VALUES (465, 'Funza');
INSERT INTO City(id,name) VALUES (466, 'Fúquene');
INSERT INTO City(id,name) VALUES (467, 'Gachala');
INSERT INTO City(id,name) VALUES (468, 'Gachancipá');
INSERT INTO City(id,name) VALUES (469, 'Gachetá');
INSERT INTO City(id,name) VALUES (470, 'Girardot');
INSERT INTO City(id,name) VALUES (471, 'Granada');
INSERT INTO City(id,name) VALUES (472, 'Guachetá');
INSERT INTO City(id,name) VALUES (473, 'Guaduas');
INSERT INTO City(id,name) VALUES (474, 'Guasca');
INSERT INTO City(id,name) VALUES (475, 'Guataquí');
INSERT INTO City(id,name) VALUES (476, 'Guatavita');
INSERT INTO City(id,name) VALUES (477, 'Guayabetal');
INSERT INTO City(id,name) VALUES (478, 'Gutiérrez');
INSERT INTO City(id,name) VALUES (479, 'Jerusalén');
INSERT INTO City(id,name) VALUES (480, 'Junín');
INSERT INTO City(id,name) VALUES (481, 'La Calera');
INSERT INTO City(id,name) VALUES (482, 'La Mesa');
INSERT INTO City(id,name) VALUES (483, 'La Palma');
INSERT INTO City(id,name) VALUES (484, 'La Peña');
INSERT INTO City(id,name) VALUES (485, 'La Vega');
INSERT INTO City(id,name) VALUES (486, 'Lenguazaque');
INSERT INTO City(id,name) VALUES (487, 'Macheta');
INSERT INTO City(id,name) VALUES (488, 'Madrid');
INSERT INTO City(id,name) VALUES (489, 'Manta');
INSERT INTO City(id,name) VALUES (490, 'Medina');
INSERT INTO City(id,name) VALUES (491, 'Mosquera');
INSERT INTO City(id,name) VALUES (492, 'Nariño');
INSERT INTO City(id,name) VALUES (493, 'Nemocón');
INSERT INTO City(id,name) VALUES (494, 'Nilo');
INSERT INTO City(id,name) VALUES (495, 'Nimaima');
INSERT INTO City(id,name) VALUES (496, 'Nocaima');
INSERT INTO City(id,name) VALUES (497, 'Venecia');
INSERT INTO City(id,name) VALUES (498, 'Pacho');
INSERT INTO City(id,name) VALUES (499, 'Paime');
INSERT INTO City(id,name) VALUES (500, 'Pandi');
INSERT INTO City(id,name) VALUES (501, 'Paratebueno');
INSERT INTO City(id,name) VALUES (502, 'Pasca');
INSERT INTO City(id,name) VALUES (503, 'Puerto Salgar');
INSERT INTO City(id,name) VALUES (504, 'Pulí');
INSERT INTO City(id,name) VALUES (505, 'Quebradanegra');
INSERT INTO City(id,name) VALUES (506, 'Quetame');
INSERT INTO City(id,name) VALUES (507, 'Quipile');
INSERT INTO City(id,name) VALUES (508, 'Apulo');
INSERT INTO City(id,name) VALUES (509, 'Ricaurte');
INSERT INTO City(id,name) VALUES (510, 'San Bernardo');
INSERT INTO City(id,name) VALUES (511, 'San Cayetano');
INSERT INTO City(id,name) VALUES (512, 'San Francisco');
INSERT INTO City(id,name) VALUES (513, 'Sesquilé');
INSERT INTO City(id,name) VALUES (514, 'Sibaté');
INSERT INTO City(id,name) VALUES (515, 'Silvania');
INSERT INTO City(id,name) VALUES (516, 'Simijaca');
INSERT INTO City(id,name) VALUES (517, 'Soacha');
INSERT INTO City(id,name) VALUES (518, 'Subachoque');
INSERT INTO City(id,name) VALUES (519, 'Suesca');
INSERT INTO City(id,name) VALUES (520, 'Supatá');
INSERT INTO City(id,name) VALUES (521, 'Susa');
INSERT INTO City(id,name) VALUES (522, 'Sutatausa');
INSERT INTO City(id,name) VALUES (523, 'Tabio');
INSERT INTO City(id,name) VALUES (524, 'Tausa');
INSERT INTO City(id,name) VALUES (525, 'Tena');
INSERT INTO City(id,name) VALUES (526, 'Tenjo');
INSERT INTO City(id,name) VALUES (527, 'Tibacuy');
INSERT INTO City(id,name) VALUES (528, 'Tibirita');
INSERT INTO City(id,name) VALUES (529, 'Tocaima');
INSERT INTO City(id,name) VALUES (530, 'Tocancipá');
INSERT INTO City(id,name) VALUES (531, 'Topaipí');
INSERT INTO City(id,name) VALUES (532, 'Ubalá');
INSERT INTO City(id,name) VALUES (533, 'Ubaque');
INSERT INTO City(id,name) VALUES (534, 'Une');
INSERT INTO City(id,name) VALUES (535, 'Útica');
INSERT INTO City(id,name) VALUES (536, 'Vianí');
INSERT INTO City(id,name) VALUES (537, 'Villagómez');
INSERT INTO City(id,name) VALUES (538, 'Villapinzón');
INSERT INTO City(id,name) VALUES (539, 'Villeta');
INSERT INTO City(id,name) VALUES (540, 'Viotá');
INSERT INTO City(id,name) VALUES (541, 'Zipacón');
INSERT INTO City(id,name) VALUES (542, 'San Juan de Río Seco');
INSERT INTO City(id,name) VALUES (543, 'Villa de San Diego de Ubate');
INSERT INTO City(id,name) VALUES (544, 'Guayabal de Siquima');
INSERT INTO City(id,name) VALUES (545, 'San Antonio del Tequendama');
INSERT INTO City(id,name) VALUES (546, 'Agua de Dios');
INSERT INTO City(id,name) VALUES (547, 'Carmen de Carupa');
INSERT INTO City(id,name) VALUES (548, 'Vergara');
INSERT INTO City(id,name) VALUES (549, 'Albán');
INSERT INTO City(id,name) VALUES (550, 'Anolaima');
INSERT INTO City(id,name) VALUES (551, 'Chía');
INSERT INTO City(id,name) VALUES (552, 'El Peñón');
INSERT INTO City(id,name) VALUES (553, 'Sopó');
INSERT INTO City(id,name) VALUES (554, 'Gama');
INSERT INTO City(id,name) VALUES (555, 'Sasaima');
INSERT INTO City(id,name) VALUES (556, 'Yacopí');
INSERT INTO City(id,name) VALUES (557, 'Fusagasugá');
INSERT INTO City(id,name) VALUES (558, 'Zipaquirá');
INSERT INTO City(id,name) VALUES (559, 'Facatativá');
INSERT INTO City(id,name) VALUES (560, 'Inírida');
INSERT INTO City(id,name) VALUES (561, 'Barranco Minas');
INSERT INTO City(id,name) VALUES (562, 'Mapiripana');
INSERT INTO City(id,name) VALUES (563, 'San Felipe');
INSERT INTO City(id,name) VALUES (564, 'Puerto Colombia');
INSERT INTO City(id,name) VALUES (565, 'La Guadalupe');
INSERT INTO City(id,name) VALUES (566, 'Cacahual');
INSERT INTO City(id,name) VALUES (567, 'Pana Pana');
INSERT INTO City(id,name) VALUES (568, 'Morichal');
INSERT INTO City(id,name) VALUES (569, 'Calamar');
INSERT INTO City(id,name) VALUES (570, 'San José del Guaviare');
INSERT INTO City(id,name) VALUES (571, 'Miraflores');
INSERT INTO City(id,name) VALUES (572, 'El Retorno');
INSERT INTO City(id,name) VALUES (573, 'Restrepo');
INSERT INTO City(id,name) VALUES (574, 'San Juanito');
INSERT INTO City(id,name) VALUES (575, 'San Martín');
INSERT INTO City(id,name) VALUES (576, 'Vista Hermosa');
INSERT INTO City(id,name) VALUES (577, 'Barranca de Upía');
INSERT INTO City(id,name) VALUES (578, 'Fuente de Oro');
INSERT INTO City(id,name) VALUES (579, 'Neiva');
INSERT INTO City(id,name) VALUES (580, 'Acevedo');
INSERT INTO City(id,name) VALUES (581, 'Agrado');
INSERT INTO City(id,name) VALUES (582, 'Aipe');
INSERT INTO City(id,name) VALUES (583, 'Algeciras');
INSERT INTO City(id,name) VALUES (584, 'Altamira');
INSERT INTO City(id,name) VALUES (585, 'Baraya');
INSERT INTO City(id,name) VALUES (586, 'Campoalegre');
INSERT INTO City(id,name) VALUES (587, 'Colombia');
INSERT INTO City(id,name) VALUES (588, 'Elías');
INSERT INTO City(id,name) VALUES (589, 'Garzón');
INSERT INTO City(id,name) VALUES (590, 'Gigante');
INSERT INTO City(id,name) VALUES (591, 'Guadalupe');
INSERT INTO City(id,name) VALUES (592, 'Hobo');
INSERT INTO City(id,name) VALUES (593, 'Iquira');
INSERT INTO City(id,name) VALUES (594, 'Isnos');
INSERT INTO City(id,name) VALUES (595, 'La Argentina');
INSERT INTO City(id,name) VALUES (596, 'La Plata');
INSERT INTO City(id,name) VALUES (597, 'Nátaga');
INSERT INTO City(id,name) VALUES (598, 'Oporapa');
INSERT INTO City(id,name) VALUES (599, 'Paicol');
INSERT INTO City(id,name) VALUES (600, 'Palermo');
INSERT INTO City(id,name) VALUES (601, 'Palestina');
INSERT INTO City(id,name) VALUES (602, 'Pital');
INSERT INTO City(id,name) VALUES (603, 'Pitalito');
INSERT INTO City(id,name) VALUES (604, 'Rivera');
INSERT INTO City(id,name) VALUES (605, 'Saladoblanco');
INSERT INTO City(id,name) VALUES (606, 'Santa María');
INSERT INTO City(id,name) VALUES (607, 'Suaza');
INSERT INTO City(id,name) VALUES (608, 'Tarqui');
INSERT INTO City(id,name) VALUES (609, 'Tesalia');
INSERT INTO City(id,name) VALUES (610, 'Tello');
INSERT INTO City(id,name) VALUES (611, 'Teruel');
INSERT INTO City(id,name) VALUES (612, 'Timaná');
INSERT INTO City(id,name) VALUES (613, 'Villavieja');
INSERT INTO City(id,name) VALUES (614, 'Yaguará');
INSERT INTO City(id,name) VALUES (615, 'San Agustín');
INSERT INTO City(id,name) VALUES (616, 'Riohacha');
INSERT INTO City(id,name) VALUES (617, 'Albania');
INSERT INTO City(id,name) VALUES (618, 'Barrancas');
INSERT INTO City(id,name) VALUES (619, 'Dibula');
INSERT INTO City(id,name) VALUES (620, 'Distracción');
INSERT INTO City(id,name) VALUES (621, 'El Molino');
INSERT INTO City(id,name) VALUES (622, 'Fonseca');
INSERT INTO City(id,name) VALUES (623, 'Hatonuevo');
INSERT INTO City(id,name) VALUES (624, 'Maicao');
INSERT INTO City(id,name) VALUES (625, 'Manaure');
INSERT INTO City(id,name) VALUES (626, 'Uribia');
INSERT INTO City(id,name) VALUES (627, 'Urumita');
INSERT INTO City(id,name) VALUES (628, 'Villanueva');
INSERT INTO City(id,name) VALUES (629, 'La Jagua del Pilar');
INSERT INTO City(id,name) VALUES (630, 'San Juan del Cesar');
INSERT INTO City(id,name) VALUES (631, 'Santa Marta');
INSERT INTO City(id,name) VALUES (632, 'Algarrobo');
INSERT INTO City(id,name) VALUES (633, 'Aracataca');
INSERT INTO City(id,name) VALUES (634, 'Ariguaní');
INSERT INTO City(id,name) VALUES (635, 'Leticia');
INSERT INTO City(id,name) VALUES (636, 'El Encanto');
INSERT INTO City(id,name) VALUES (637, 'La Chorrera');
INSERT INTO City(id,name) VALUES (638, 'La Pedrera');
INSERT INTO City(id,name) VALUES (639, 'La Victoria');
INSERT INTO City(id,name) VALUES (640, 'Puerto Arica');
INSERT INTO City(id,name) VALUES (641, 'Puerto Nariño');
INSERT INTO City(id,name) VALUES (642, 'Puerto Santander');
INSERT INTO City(id,name) VALUES (643, 'Tarapacá');
INSERT INTO City(id,name) VALUES (644, 'Puerto Alegría');
INSERT INTO City(id,name) VALUES (645, 'Miriti Paraná');
INSERT INTO City(id,name) VALUES (646, 'Medellín');
INSERT INTO City(id,name) VALUES (647, 'Abejorral');
INSERT INTO City(id,name) VALUES (648, 'Abriaquí');
INSERT INTO City(id,name) VALUES (649, 'Alejandría');
INSERT INTO City(id,name) VALUES (650, 'Amagá');
INSERT INTO City(id,name) VALUES (651, 'Amalfi');
INSERT INTO City(id,name) VALUES (652, 'Andes');
INSERT INTO City(id,name) VALUES (653, 'Angelópolis');
INSERT INTO City(id,name) VALUES (654, 'Angostura');
INSERT INTO City(id,name) VALUES (655, 'Anorí');
INSERT INTO City(id,name) VALUES (656, 'Anza');
INSERT INTO City(id,name) VALUES (657, 'Apartadó');
INSERT INTO City(id,name) VALUES (658, 'Arboletes');
INSERT INTO City(id,name) VALUES (659, 'Argelia');
INSERT INTO City(id,name) VALUES (660, 'Armenia');
INSERT INTO City(id,name) VALUES (661, 'Barbosa');
INSERT INTO City(id,name) VALUES (662, 'Bello');
INSERT INTO City(id,name) VALUES (663, 'Betania');
INSERT INTO City(id,name) VALUES (664, 'Betulia');
INSERT INTO City(id,name) VALUES (665, 'Ciudad Bolívar');
INSERT INTO City(id,name) VALUES (666, 'Briceño');
INSERT INTO City(id,name) VALUES (667, 'Buriticá');
INSERT INTO City(id,name) VALUES (668, 'Cáceres');
INSERT INTO City(id,name) VALUES (669, 'Caicedo');
INSERT INTO City(id,name) VALUES (670, 'Caldas');
INSERT INTO City(id,name) VALUES (671, 'Campamento');
INSERT INTO City(id,name) VALUES (672, 'Cañasgordas');
INSERT INTO City(id,name) VALUES (673, 'Caracolí');
INSERT INTO City(id,name) VALUES (674, 'Caramanta');
INSERT INTO City(id,name) VALUES (675, 'Carepa');
INSERT INTO City(id,name) VALUES (676, 'Carolina');
INSERT INTO City(id,name) VALUES (677, 'Caucasia');
INSERT INTO City(id,name) VALUES (678, 'Chigorodó');
INSERT INTO City(id,name) VALUES (679, 'Cisneros');
INSERT INTO City(id,name) VALUES (680, 'Cocorná');
INSERT INTO City(id,name) VALUES (681, 'Concepción');
INSERT INTO City(id,name) VALUES (682, 'Concordia');
INSERT INTO City(id,name) VALUES (683, 'Copacabana');
INSERT INTO City(id,name) VALUES (684, 'Dabeiba');
INSERT INTO City(id,name) VALUES (685, 'Don Matías');
INSERT INTO City(id,name) VALUES (686, 'Ebéjico');
INSERT INTO City(id,name) VALUES (687, 'El Bagre');
INSERT INTO City(id,name) VALUES (688, 'Entrerrios');
INSERT INTO City(id,name) VALUES (689, 'Envigado');
INSERT INTO City(id,name) VALUES (690, 'Fredonia');
INSERT INTO City(id,name) VALUES (691, 'Giraldo');
INSERT INTO City(id,name) VALUES (692, 'Girardota');
INSERT INTO City(id,name) VALUES (693, 'Gómez Plata');
INSERT INTO City(id,name) VALUES (694, 'Guadalupe');
INSERT INTO City(id,name) VALUES (695, 'Guarne');
INSERT INTO City(id,name) VALUES (696, 'Guatapé');
INSERT INTO City(id,name) VALUES (697, 'Heliconia');
INSERT INTO City(id,name) VALUES (698, 'Hispania');
INSERT INTO City(id,name) VALUES (699, 'Itagui');
INSERT INTO City(id,name) VALUES (700, 'Ituango');
INSERT INTO City(id,name) VALUES (701, 'Belmira');
INSERT INTO City(id,name) VALUES (702, 'Jericó');
INSERT INTO City(id,name) VALUES (703, 'La Ceja');
INSERT INTO City(id,name) VALUES (704, 'La Estrella');
INSERT INTO City(id,name) VALUES (705, 'La Pintada');
INSERT INTO City(id,name) VALUES (706, 'La Unión');
INSERT INTO City(id,name) VALUES (707, 'Liborina');
INSERT INTO City(id,name) VALUES (708, 'Maceo');
INSERT INTO City(id,name) VALUES (709, 'Marinilla');
INSERT INTO City(id,name) VALUES (710, 'Montebello');
INSERT INTO City(id,name) VALUES (711, 'Murindó');
INSERT INTO City(id,name) VALUES (712, 'Mutatá');
INSERT INTO City(id,name) VALUES (713, 'Nariño');
INSERT INTO City(id,name) VALUES (714, 'Necoclí');
INSERT INTO City(id,name) VALUES (715, 'Nechí');
INSERT INTO City(id,name) VALUES (716, 'Olaya');
INSERT INTO City(id,name) VALUES (717, 'Peñol');
INSERT INTO City(id,name) VALUES (718, 'Peque');
INSERT INTO City(id,name) VALUES (719, 'Pueblorrico');
INSERT INTO City(id,name) VALUES (720, 'Puerto Berrío');
INSERT INTO City(id,name) VALUES (721, 'Cerro San Antonio');
INSERT INTO City(id,name) VALUES (722, 'Chivolo');
INSERT INTO City(id,name) VALUES (723, 'Concordia');
INSERT INTO City(id,name) VALUES (724, 'El Banco');
INSERT INTO City(id,name) VALUES (725, 'El Piñon');
INSERT INTO City(id,name) VALUES (726, 'El Retén');
INSERT INTO City(id,name) VALUES (727, 'Fundación');
INSERT INTO City(id,name) VALUES (728, 'Guamal');
INSERT INTO City(id,name) VALUES (729, 'Nueva Granada');
INSERT INTO City(id,name) VALUES (730, 'Pedraza');
INSERT INTO City(id,name) VALUES (731, 'Pivijay');
INSERT INTO City(id,name) VALUES (732, 'Plato');
INSERT INTO City(id,name) VALUES (733, 'Remolino');
INSERT INTO City(id,name) VALUES (734, 'Salamina');
INSERT INTO City(id,name) VALUES (735, 'San Zenón');
INSERT INTO City(id,name) VALUES (736, 'Santa Ana');
INSERT INTO City(id,name) VALUES (737, 'Sitionuevo');
INSERT INTO City(id,name) VALUES (738, 'Tenerife');
INSERT INTO City(id,name) VALUES (739, 'Zapayán');
INSERT INTO City(id,name) VALUES (740, 'Zona Bananera');
INSERT INTO City(id,name) VALUES (741, 'San Sebastián de Buenavista');
INSERT INTO City(id,name) VALUES (742, 'Sabanas de San Angel');
INSERT INTO City(id,name) VALUES (743, 'Pijiño del Carmen');
INSERT INTO City(id,name) VALUES (744, 'Santa Bárbara de Pinto');
INSERT INTO City(id,name) VALUES (745, 'Pueblo Viejo');
INSERT INTO City(id,name) VALUES (746, 'Ciénaga');
INSERT INTO City(id,name) VALUES (747, 'Uribe');
INSERT INTO City(id,name) VALUES (748, 'Villavicencio');
INSERT INTO City(id,name) VALUES (749, 'Acacias');
INSERT INTO City(id,name) VALUES (750, 'Cabuyaro');
INSERT INTO City(id,name) VALUES (751, 'Cubarral');
INSERT INTO City(id,name) VALUES (752, 'Cumaral');
INSERT INTO City(id,name) VALUES (753, 'El Calvario');
INSERT INTO City(id,name) VALUES (754, 'El Castillo');
INSERT INTO City(id,name) VALUES (755, 'El Dorado');
INSERT INTO City(id,name) VALUES (756, 'Granada');
INSERT INTO City(id,name) VALUES (757, 'Guamal');
INSERT INTO City(id,name) VALUES (758, 'Mapiripán');
INSERT INTO City(id,name) VALUES (759, 'Mesetas');
INSERT INTO City(id,name) VALUES (760, 'La Macarena');
INSERT INTO City(id,name) VALUES (761, 'Lejanías');
INSERT INTO City(id,name) VALUES (762, 'Puerto Concordia');
INSERT INTO City(id,name) VALUES (763, 'Puerto Gaitán');
INSERT INTO City(id,name) VALUES (764, 'San Carlos de Guaroa');
INSERT INTO City(id,name) VALUES (765, 'San Juan de Arama');
INSERT INTO City(id,name) VALUES (766, 'Castilla la Nueva');
INSERT INTO City(id,name) VALUES (767, 'Santacruz');
INSERT INTO City(id,name) VALUES (768, 'Pasto');
INSERT INTO City(id,name) VALUES (769, 'Albán');
INSERT INTO City(id,name) VALUES (770, 'Aldana');
INSERT INTO City(id,name) VALUES (771, 'Ancuyá');
INSERT INTO City(id,name) VALUES (772, 'Barbacoas');
INSERT INTO City(id,name) VALUES (773, 'Colón');
INSERT INTO City(id,name) VALUES (774, 'Consaca');
INSERT INTO City(id,name) VALUES (775, 'Contadero');
INSERT INTO City(id,name) VALUES (776, 'Córdoba');
INSERT INTO City(id,name) VALUES (777, 'Cuaspud');
INSERT INTO City(id,name) VALUES (778, 'Cumbal');
INSERT INTO City(id,name) VALUES (779, 'Cumbitara');
INSERT INTO City(id,name) VALUES (780, 'El Charco');
INSERT INTO City(id,name) VALUES (781, 'El Peñol');
INSERT INTO City(id,name) VALUES (782, 'El Rosario');
INSERT INTO City(id,name) VALUES (783, 'El Tambo');
INSERT INTO City(id,name) VALUES (784, 'Funes');
INSERT INTO City(id,name) VALUES (785, 'Guachucal');
INSERT INTO City(id,name) VALUES (786, 'Guaitarilla');
INSERT INTO City(id,name) VALUES (787, 'Gualmatán');
INSERT INTO City(id,name) VALUES (788, 'Iles');
INSERT INTO City(id,name) VALUES (789, 'Imués');
INSERT INTO City(id,name) VALUES (790, 'Ipiales');
INSERT INTO City(id,name) VALUES (791, 'La Cruz');
INSERT INTO City(id,name) VALUES (792, 'La Florida');
INSERT INTO City(id,name) VALUES (793, 'La Llanada');
INSERT INTO City(id,name) VALUES (794, 'La Tola');
INSERT INTO City(id,name) VALUES (795, 'La Unión');
INSERT INTO City(id,name) VALUES (796, 'Leiva');
INSERT INTO City(id,name) VALUES (797, 'Linares');
INSERT INTO City(id,name) VALUES (798, 'Los Andes');
INSERT INTO City(id,name) VALUES (799, 'Magüí');
INSERT INTO City(id,name) VALUES (800, 'Mallama');
INSERT INTO City(id,name) VALUES (801, 'Mosquera');
INSERT INTO City(id,name) VALUES (802, 'Nariño');
INSERT INTO City(id,name) VALUES (803, 'Olaya Herrera');
INSERT INTO City(id,name) VALUES (804, 'Ospina');
INSERT INTO City(id,name) VALUES (805, 'Francisco Pizarro');
INSERT INTO City(id,name) VALUES (806, 'Policarpa');
INSERT INTO City(id,name) VALUES (807, 'Potosí');
INSERT INTO City(id,name) VALUES (808, 'Providencia');
INSERT INTO City(id,name) VALUES (809, 'Puerres');
INSERT INTO City(id,name) VALUES (810, 'Pupiales');
INSERT INTO City(id,name) VALUES (811, 'Ricaurte');
INSERT INTO City(id,name) VALUES (812, 'Roberto Payán');
INSERT INTO City(id,name) VALUES (813, 'Samaniego');
INSERT INTO City(id,name) VALUES (814, 'Sandoná');
INSERT INTO City(id,name) VALUES (815, 'San Bernardo');
INSERT INTO City(id,name) VALUES (816, 'San Lorenzo');
INSERT INTO City(id,name) VALUES (817, 'San Pablo');
INSERT INTO City(id,name) VALUES (818, 'Santa Bárbara');
INSERT INTO City(id,name) VALUES (819, 'Sapuyes');
INSERT INTO City(id,name) VALUES (820, 'Taminango');
INSERT INTO City(id,name) VALUES (821, 'Tangua');
INSERT INTO City(id,name) VALUES (822, 'Túquerres');
INSERT INTO City(id,name) VALUES (823, 'Yacuanquer');
INSERT INTO City(id,name) VALUES (824, 'San Pedro de Cartago');
INSERT INTO City(id,name) VALUES (825, 'El Tablón de Gómez');
INSERT INTO City(id,name) VALUES (826, 'Buesaco');
INSERT INTO City(id,name) VALUES (827, 'San Andrés de Tumaco');
INSERT INTO City(id,name) VALUES (828, 'Belén');
INSERT INTO City(id,name) VALUES (829, 'Chachagüí');
INSERT INTO City(id,name) VALUES (830, 'Arboleda');
INSERT INTO City(id,name) VALUES (831, 'Silos');
INSERT INTO City(id,name) VALUES (832, 'Cácota');
INSERT INTO City(id,name) VALUES (833, 'Toledo');
INSERT INTO City(id,name) VALUES (834, 'Mutiscua');
INSERT INTO City(id,name) VALUES (835, 'El Zulia');
INSERT INTO City(id,name) VALUES (836, 'Salazar');
INSERT INTO City(id,name) VALUES (837, 'Cucutilla');
INSERT INTO City(id,name) VALUES (838, 'Puerto Santander');
INSERT INTO City(id,name) VALUES (839, 'Gramalote');
INSERT INTO City(id,name) VALUES (840, 'El Tarra');
INSERT INTO City(id,name) VALUES (841, 'Teorama');
INSERT INTO City(id,name) VALUES (842, 'Arboledas');
INSERT INTO City(id,name) VALUES (843, 'Lourdes');
INSERT INTO City(id,name) VALUES (844, 'Bochalema');
INSERT INTO City(id,name) VALUES (845, 'Convención');
INSERT INTO City(id,name) VALUES (846, 'Hacarí');
INSERT INTO City(id,name) VALUES (847, 'Herrán');
INSERT INTO City(id,name) VALUES (848, 'Tibú');
INSERT INTO City(id,name) VALUES (849, 'San Cayetano');
INSERT INTO City(id,name) VALUES (850, 'San Calixto');
INSERT INTO City(id,name) VALUES (851, 'La Playa');
INSERT INTO City(id,name) VALUES (852, 'Chinácota');
INSERT INTO City(id,name) VALUES (853, 'Ragonvalia');
INSERT INTO City(id,name) VALUES (854, 'La Esperanza');
INSERT INTO City(id,name) VALUES (855, 'Villa del Rosario');
INSERT INTO City(id,name) VALUES (856, 'Chitagá');
INSERT INTO City(id,name) VALUES (857, 'Sardinata');
INSERT INTO City(id,name) VALUES (858, 'Abrego');
INSERT INTO City(id,name) VALUES (859, 'Los Patios');
INSERT INTO City(id,name) VALUES (860, 'Ocaña');
INSERT INTO City(id,name) VALUES (861, 'Bucarasica');
INSERT INTO City(id,name) VALUES (862, 'Santiago');
INSERT INTO City(id,name) VALUES (863, 'Labateca');
INSERT INTO City(id,name) VALUES (864, 'Cachirá');
INSERT INTO City(id,name) VALUES (865, 'Villa Caro');
INSERT INTO City(id,name) VALUES (866, 'Durania');
INSERT INTO City(id,name) VALUES (867, 'Pamplona');
INSERT INTO City(id,name) VALUES (868, 'Pamplonita');
INSERT INTO City(id,name) VALUES (869, 'Cúcuta');
INSERT INTO City(id,name) VALUES (870, 'El Carmen');
INSERT INTO City(id,name) VALUES (871, 'Mocoa');
INSERT INTO City(id,name) VALUES (872, 'Colón');
INSERT INTO City(id,name) VALUES (873, 'Orito');
INSERT INTO City(id,name) VALUES (874, 'Puerto Caicedo');
INSERT INTO City(id,name) VALUES (875, 'Puerto Guzmán');
INSERT INTO City(id,name) VALUES (876, 'Leguízamo');
INSERT INTO City(id,name) VALUES (877, 'Sibundoy');
INSERT INTO City(id,name) VALUES (878, 'San Francisco');
INSERT INTO City(id,name) VALUES (879, 'San Miguel');
INSERT INTO City(id,name) VALUES (880, 'Santiago');
INSERT INTO City(id,name) VALUES (881, 'Valle de Guamez');
INSERT INTO City(id,name) VALUES (882, 'Puerto Asís');
INSERT INTO City(id,name) VALUES (883, 'Villagarzón');
INSERT INTO City(id,name) VALUES (884, 'Armenia');
INSERT INTO City(id,name) VALUES (885, 'Buenavista');
INSERT INTO City(id,name) VALUES (886, 'Circasia');
INSERT INTO City(id,name) VALUES (887, 'Córdoba');
INSERT INTO City(id,name) VALUES (888, 'Filandia');
INSERT INTO City(id,name) VALUES (889, 'La Tebaida');
INSERT INTO City(id,name) VALUES (890, 'Montenegro');
INSERT INTO City(id,name) VALUES (891, 'Pijao');
INSERT INTO City(id,name) VALUES (892, 'Quimbaya');
INSERT INTO City(id,name) VALUES (893, 'Salento');
INSERT INTO City(id,name) VALUES (894, 'Calarcá');
INSERT INTO City(id,name) VALUES (895, 'Génova');
INSERT INTO City(id,name) VALUES (896, 'Pereira');
INSERT INTO City(id,name) VALUES (897, 'Apía');
INSERT INTO City(id,name) VALUES (898, 'Balboa');
INSERT INTO City(id,name) VALUES (899, 'Dosquebradas');
INSERT INTO City(id,name) VALUES (900, 'Guática');
INSERT INTO City(id,name) VALUES (901, 'La Celia');
INSERT INTO City(id,name) VALUES (902, 'La Virginia');
INSERT INTO City(id,name) VALUES (903, 'Marsella');
INSERT INTO City(id,name) VALUES (904, 'Mistrató');
INSERT INTO City(id,name) VALUES (905, 'Pueblo Rico');
INSERT INTO City(id,name) VALUES (906, 'Quinchía');
INSERT INTO City(id,name) VALUES (907, 'Santuario');
INSERT INTO City(id,name) VALUES (908, 'Santa Rosa de Cabal');
INSERT INTO City(id,name) VALUES (909, 'Belén de Umbría');
INSERT INTO City(id,name) VALUES (910, 'Providencia');
INSERT INTO City(id,name) VALUES (911, 'San Andrés');
INSERT INTO City(id,name) VALUES (912, 'Puerto Wilches');
INSERT INTO City(id,name) VALUES (913, 'Puerto Parra');
INSERT INTO City(id,name) VALUES (914, 'Bucaramanga');
INSERT INTO City(id,name) VALUES (915, 'Aguada');
INSERT INTO City(id,name) VALUES (916, 'Albania');
INSERT INTO City(id,name) VALUES (917, 'Aratoca');
INSERT INTO City(id,name) VALUES (918, 'Barbosa');
INSERT INTO City(id,name) VALUES (919, 'Barichara');
INSERT INTO City(id,name) VALUES (920, 'Barrancabermeja');
INSERT INTO City(id,name) VALUES (921, 'Betulia');
INSERT INTO City(id,name) VALUES (922, 'Bolívar');
INSERT INTO City(id,name) VALUES (923, 'Cabrera');
INSERT INTO City(id,name) VALUES (924, 'California');
INSERT INTO City(id,name) VALUES (925, 'Carcasí');
INSERT INTO City(id,name) VALUES (926, 'Cepitá');
INSERT INTO City(id,name) VALUES (927, 'Cerrito');
INSERT INTO City(id,name) VALUES (928, 'Charalá');
INSERT INTO City(id,name) VALUES (929, 'Charta');
INSERT INTO City(id,name) VALUES (930, 'Chipatá');
INSERT INTO City(id,name) VALUES (931, 'Cimitarra');
INSERT INTO City(id,name) VALUES (932, 'Concepción');
INSERT INTO City(id,name) VALUES (933, 'Confines');
INSERT INTO City(id,name) VALUES (934, 'Contratación');
INSERT INTO City(id,name) VALUES (935, 'Coromoro');
INSERT INTO City(id,name) VALUES (936, 'Curití');
INSERT INTO City(id,name) VALUES (937, 'El Guacamayo');
INSERT INTO City(id,name) VALUES (938, 'El Playón');
INSERT INTO City(id,name) VALUES (939, 'Encino');
INSERT INTO City(id,name) VALUES (940, 'Enciso');
INSERT INTO City(id,name) VALUES (941, 'Florián');
INSERT INTO City(id,name) VALUES (942, 'Floridablanca');
INSERT INTO City(id,name) VALUES (943, 'Galán');
INSERT INTO City(id,name) VALUES (944, 'Gambita');
INSERT INTO City(id,name) VALUES (945, 'Girón');
INSERT INTO City(id,name) VALUES (946, 'Guaca');
INSERT INTO City(id,name) VALUES (947, 'Guadalupe');
INSERT INTO City(id,name) VALUES (948, 'Guapotá');
INSERT INTO City(id,name) VALUES (949, 'Guavatá');
INSERT INTO City(id,name) VALUES (950, 'Güepsa');
INSERT INTO City(id,name) VALUES (951, 'Jesús María');
INSERT INTO City(id,name) VALUES (952, 'Jordán');
INSERT INTO City(id,name) VALUES (953, 'La Belleza');
INSERT INTO City(id,name) VALUES (954, 'Landázuri');
INSERT INTO City(id,name) VALUES (955, 'La Paz');
INSERT INTO City(id,name) VALUES (956, 'Lebríja');
INSERT INTO City(id,name) VALUES (957, 'Los Santos');
INSERT INTO City(id,name) VALUES (958, 'Macaravita');
INSERT INTO City(id,name) VALUES (959, 'Málaga');
INSERT INTO City(id,name) VALUES (960, 'Matanza');
INSERT INTO City(id,name) VALUES (961, 'Mogotes');
INSERT INTO City(id,name) VALUES (962, 'Molagavita');
INSERT INTO City(id,name) VALUES (963, 'Ocamonte');
INSERT INTO City(id,name) VALUES (964, 'Oiba');
INSERT INTO City(id,name) VALUES (965, 'Onzaga');
INSERT INTO City(id,name) VALUES (966, 'Palmar');
INSERT INTO City(id,name) VALUES (967, 'Páramo');
INSERT INTO City(id,name) VALUES (968, 'Piedecuesta');
INSERT INTO City(id,name) VALUES (969, 'Pinchote');
INSERT INTO City(id,name) VALUES (970, 'Puente Nacional');
INSERT INTO City(id,name) VALUES (971, 'Rionegro');
INSERT INTO City(id,name) VALUES (972, 'San Andrés');
INSERT INTO City(id,name) VALUES (973, 'San Gil');
INSERT INTO City(id,name) VALUES (974, 'San Joaquín');
INSERT INTO City(id,name) VALUES (975, 'San Miguel');
INSERT INTO City(id,name) VALUES (976, 'Santa Bárbara');
INSERT INTO City(id,name) VALUES (977, 'Simacota');
INSERT INTO City(id,name) VALUES (978, 'Socorro');
INSERT INTO City(id,name) VALUES (979, 'Suaita');
INSERT INTO City(id,name) VALUES (980, 'Sucre');
INSERT INTO City(id,name) VALUES (981, 'Suratá');
INSERT INTO City(id,name) VALUES (982, 'Tona');
INSERT INTO City(id,name) VALUES (983, 'Vélez');
INSERT INTO City(id,name) VALUES (984, 'Vetas');
INSERT INTO City(id,name) VALUES (985, 'Villanueva');
INSERT INTO City(id,name) VALUES (986, 'Zapatoca');
INSERT INTO City(id,name) VALUES (987, 'Palmas del Socorro');
INSERT INTO City(id,name) VALUES (988, 'San Vicente de Chucurí');
INSERT INTO City(id,name) VALUES (989, 'San José de Miranda');
INSERT INTO City(id,name) VALUES (990, 'Santa Helena del Opón');
INSERT INTO City(id,name) VALUES (991, 'Sabana de Torres');
INSERT INTO City(id,name) VALUES (992, 'El Carmen de Chucurí');
INSERT INTO City(id,name) VALUES (993, 'Valle de San José');
INSERT INTO City(id,name) VALUES (994, 'San Benito');
INSERT INTO City(id,name) VALUES (995, 'Hato');
INSERT INTO City(id,name) VALUES (996, 'Chimá');
INSERT INTO City(id,name) VALUES (997, 'Capitanejo');
INSERT INTO City(id,name) VALUES (998, 'El Peñón');
INSERT INTO City(id,name) VALUES (999, 'Sincelejo');
INSERT INTO City(id,name) VALUES (1000, 'Buenavista');
INSERT INTO City(id,name) VALUES (1001, 'Caimito');
INSERT INTO City(id,name) VALUES (1002, 'Coloso');
INSERT INTO City(id,name) VALUES (1003, 'Coveñas');
INSERT INTO City(id,name) VALUES (1004, 'Chalán');
INSERT INTO City(id,name) VALUES (1005, 'El Roble');
INSERT INTO City(id,name) VALUES (1006, 'Galeras');
INSERT INTO City(id,name) VALUES (1007, 'Guaranda');
INSERT INTO City(id,name) VALUES (1008, 'La Unión');
INSERT INTO City(id,name) VALUES (1009, 'Los Palmitos');
INSERT INTO City(id,name) VALUES (1010, 'Majagual');
INSERT INTO City(id,name) VALUES (1011, 'Morroa');
INSERT INTO City(id,name) VALUES (1012, 'Ovejas');
INSERT INTO City(id,name) VALUES (1013, 'Palmito');
INSERT INTO City(id,name) VALUES (1014, 'San Benito Abad');
INSERT INTO City(id,name) VALUES (1015, 'San Marcos');
INSERT INTO City(id,name) VALUES (1016, 'San Onofre');
INSERT INTO City(id,name) VALUES (1017, 'San Pedro');
INSERT INTO City(id,name) VALUES (1018, 'Sucre');
INSERT INTO City(id,name) VALUES (1019, 'Tolú Viejo');
INSERT INTO City(id,name) VALUES (1020, 'San Luis de Sincé');
INSERT INTO City(id,name) VALUES (1021, 'San Juan de Betulia');
INSERT INTO City(id,name) VALUES (1022, 'Santiago de Tolú');
INSERT INTO City(id,name) VALUES (1023, 'Sampués');
INSERT INTO City(id,name) VALUES (1024, 'Corozal');
INSERT INTO City(id,name) VALUES (1025, 'Alpujarra');
INSERT INTO City(id,name) VALUES (1026, 'Alvarado');
INSERT INTO City(id,name) VALUES (1027, 'Ambalema');
INSERT INTO City(id,name) VALUES (1028, 'Armero');
INSERT INTO City(id,name) VALUES (1029, 'Ataco');
INSERT INTO City(id,name) VALUES (1030, 'Cajamarca');
INSERT INTO City(id,name) VALUES (1031, 'Chaparral');
INSERT INTO City(id,name) VALUES (1032, 'Coello');
INSERT INTO City(id,name) VALUES (1033, 'Coyaima');
INSERT INTO City(id,name) VALUES (1034, 'Cunday');
INSERT INTO City(id,name) VALUES (1035, 'Dolores');
INSERT INTO City(id,name) VALUES (1036, 'Espinal');
INSERT INTO City(id,name) VALUES (1037, 'Falan');
INSERT INTO City(id,name) VALUES (1038, 'Flandes');
INSERT INTO City(id,name) VALUES (1039, 'Fresno');
INSERT INTO City(id,name) VALUES (1040, 'Guamo');
INSERT INTO City(id,name) VALUES (1041, 'Herveo');
INSERT INTO City(id,name) VALUES (1042, 'Honda');
INSERT INTO City(id,name) VALUES (1043, 'Icononzo');
INSERT INTO City(id,name) VALUES (1044, 'Mariquita');
INSERT INTO City(id,name) VALUES (1045, 'Melgar');
INSERT INTO City(id,name) VALUES (1046, 'Murillo');
INSERT INTO City(id,name) VALUES (1047, 'Natagaima');
INSERT INTO City(id,name) VALUES (1048, 'Ortega');
INSERT INTO City(id,name) VALUES (1049, 'Palocabildo');
INSERT INTO City(id,name) VALUES (1050, 'Piedras');
INSERT INTO City(id,name) VALUES (1051, 'Planadas');
INSERT INTO City(id,name) VALUES (1052, 'Prado');
INSERT INTO City(id,name) VALUES (1053, 'Purificación');
INSERT INTO City(id,name) VALUES (1054, 'Rio Blanco');
INSERT INTO City(id,name) VALUES (1055, 'Roncesvalles');
INSERT INTO City(id,name) VALUES (1056, 'Rovira');
INSERT INTO City(id,name) VALUES (1057, 'Saldaña');
INSERT INTO City(id,name) VALUES (1058, 'Santa Isabel');
INSERT INTO City(id,name) VALUES (1059, 'Venadillo');
INSERT INTO City(id,name) VALUES (1060, 'Villahermosa');
INSERT INTO City(id,name) VALUES (1061, 'Villarrica');
INSERT INTO City(id,name) VALUES (1062, 'Valle de San Juan');
INSERT INTO City(id,name) VALUES (1063, 'Carmen de Apicala');
INSERT INTO City(id,name) VALUES (1064, 'San Luis');
INSERT INTO City(id,name) VALUES (1065, 'San Antonio');
INSERT INTO City(id,name) VALUES (1066, 'Casabianca');
INSERT INTO City(id,name) VALUES (1067, 'Anzoátegui');
INSERT INTO City(id,name) VALUES (1068, 'Ibagué');
INSERT INTO City(id,name) VALUES (1069, 'Líbano');
INSERT INTO City(id,name) VALUES (1070, 'Lérida');
INSERT INTO City(id,name) VALUES (1071, 'Suárez');
INSERT INTO City(id,name) VALUES (1072, 'El Dovio');
INSERT INTO City(id,name) VALUES (1073, 'Roldanillo');
INSERT INTO City(id,name) VALUES (1074, 'Argelia');
INSERT INTO City(id,name) VALUES (1075, 'Sevilla');
INSERT INTO City(id,name) VALUES (1076, 'Zarzal');
INSERT INTO City(id,name) VALUES (1077, 'El Cerrito');
INSERT INTO City(id,name) VALUES (1078, 'Cartago');
INSERT INTO City(id,name) VALUES (1079, 'Caicedonia');
INSERT INTO City(id,name) VALUES (1080, 'El Cairo');
INSERT INTO City(id,name) VALUES (1081, 'La Unión');
INSERT INTO City(id,name) VALUES (1082, 'Restrepo');
INSERT INTO City(id,name) VALUES (1083, 'Dagua');
INSERT INTO City(id,name) VALUES (1084, 'Guacarí');
INSERT INTO City(id,name) VALUES (1085, 'Ansermanuevo');
INSERT INTO City(id,name) VALUES (1086, 'Bugalagrande');
INSERT INTO City(id,name) VALUES (1087, 'La Victoria');
INSERT INTO City(id,name) VALUES (1088, 'Ginebra');
INSERT INTO City(id,name) VALUES (1089, 'Yumbo');
INSERT INTO City(id,name) VALUES (1090, 'Obando');
INSERT INTO City(id,name) VALUES (1091, 'Bolívar');
INSERT INTO City(id,name) VALUES (1092, 'Cali');
INSERT INTO City(id,name) VALUES (1093, 'San Pedro');
INSERT INTO City(id,name) VALUES (1094, 'Guadalajara de Buga');
INSERT INTO City(id,name) VALUES (1095, 'Calima');
INSERT INTO City(id,name) VALUES (1096, 'Andalucía');
INSERT INTO City(id,name) VALUES (1097, 'Pradera');
INSERT INTO City(id,name) VALUES (1098, 'Yotoco');
INSERT INTO City(id,name) VALUES (1099, 'Palmira');
INSERT INTO City(id,name) VALUES (1100, 'Riofrío');
INSERT INTO City(id,name) VALUES (1101, 'Alcalá');
INSERT INTO City(id,name) VALUES (1102, 'Versalles');
INSERT INTO City(id,name) VALUES (1103, 'El Águila');
INSERT INTO City(id,name) VALUES (1104, 'Toro');
INSERT INTO City(id,name) VALUES (1105, 'Candelaria');
INSERT INTO City(id,name) VALUES (1106, 'La Cumbre');
INSERT INTO City(id,name) VALUES (1107, 'Ulloa');
INSERT INTO City(id,name) VALUES (1108, 'Trujillo');
INSERT INTO City(id,name) VALUES (1109, 'Vijes');
INSERT INTO City(id,name) VALUES (1110, 'Tuluá');
INSERT INTO City(id,name) VALUES (1111, 'Florida');
INSERT INTO City(id,name) VALUES (1112, 'Jamundí');
INSERT INTO City(id,name) VALUES (1113, 'Buenaventura');
INSERT INTO City(id,name) VALUES (1114, 'Mitú');
INSERT INTO City(id,name) VALUES (1115, 'Carurú');
INSERT INTO City(id,name) VALUES (1116, 'Taraira');
INSERT INTO City(id,name) VALUES (1117, 'Papunahua');
INSERT INTO City(id,name) VALUES (1118, 'Yavaraté');
INSERT INTO City(id,name) VALUES (1119, 'Pacoa');
INSERT INTO City(id,name) VALUES (1120, 'Puerto Carreño');
INSERT INTO City(id,name) VALUES (1121, 'La Primavera');
INSERT INTO City(id,name) VALUES (1122, 'Santa Rosalía');
INSERT INTO City(id,name) VALUES (1123, 'Cumaribo');
